In [2]:
import numpy as np

In [5]:
# Define the pairs of input and output vectors
input_vectors = np.array([[1, 1, 1, 0, 0],
                          [0, 0, 1, 1, 1]])
output_vectors = np.array([[1, 0, 0],
                           [0, 1, 0]])

# Compute the weight matrix
weight_matrix = np.dot(input_vectors.T, output_vectors)

# Define the BAM function
def BAM(input_vector):
    output_vector = np.dot(input_vector, weight_matrix)
    return output_vector

#Testing
input_vector = input_vectors[0]
output_vector = BAM(input_vector)

# Print the input and output vectors
print("Weight matrix : \n",weight_matrix)
print("Input vector:", input_vector)
print("Output vector:", output_vector)

Weight matrix : 
 [[1 0 0]
 [1 0 0]
 [1 1 0]
 [0 1 0]
 [0 1 0]]
Input vector: [1 1 1 0 0]
Output vector: [3 1 0]
